version: 0.2

phases:
  install:
    runtime-versions:
      python: "3.7"
    commands:
      - apt-get -qq install pandoc -y
      - pip install ipython sphinx sphinx_rtd_theme sphinxcontrib-bibtex sphinxcontrib-blockdiag sphinx-autobuild nbsphinx -q
  pre_build:
    commands:
      - python --version
      - pip --version
  build:
    commands:
      - cd sphinx/java-intro && make clean && make html && cd ../..
      - cd sphinx/python-intro && make clean && make html && cd ../..
      - cd sphinx/pytorch-intro && make clean && make html && cd ../..
      - cd sphinx/scikit-intro && make clean && make html && cd ../..
      - cd sphinx/spark-intro && make clean && make html && cd ../..
      - cd sphinx/datascience && make clean && make html && cd ../..
      - cd sphinx/python-dothis && make clean && make html && cd ../..
      - cd sphinx/scratch && make clean && make html && cd ../..
      - cd sphinx/tello && make clean && make html && cd ../..
      - cd sphinx/makeblock && make clean && make html && cd ../..
      - cd sphinx/r-intro && make clean && make html && cd ../..
      - cd sphinx/excel && make clean && make html && cd ../..
      - cd sphinx/docker && make clean && make html && cd ../..
  post_build:
    commands:
      - aws s3 sync sphinx/java-intro/build/html s3://learn-java.oneoffcoder.com --quiet
      - aws s3 sync sphinx/python-intro/build/html s3://learn-python.oneoffcoder.com --quiet
      - aws s3 sync sphinx/pytorch-intro/build/html s3://learn-pytorch.oneoffcoder.com --quiet
      - aws s3 sync sphinx/scikit-intro/build/html s3://learn-scikit.oneoffcoder.com --quiet
      - aws s3 sync sphinx/spark-intro/build/html s3://learn-spark.oneoffcoder.com --quiet
      - aws s3 sync sphinx/datascience/build/html s3://datascience.oneoffcoder.com --quiet
      - aws s3 sync sphinx/python-dothis/build/html s3://python.oneoffcoder.com --quiet
      - aws s3 sync sphinx/scratch/build/html s3://scratch.oneoffcoder.com --quiet
      - aws s3 sync sphinx/tello/build/html s3://tello.oneoffcoder.com --quiet
      - aws s3 sync sphinx/makeblock/build/html s3://makeblock.oneoffcoder.com --quiet
      - aws s3 sync sphinx/r-intro/build/html s3://r.oneoffcoder.com --quiet
      - aws s3 sync sphinx/excel/build/html s3://excel.oneoffcoder.com --quiet
      - aws s3 sync sphinx/docker/build/html s3://docker.oneoffcoder.com --quiet
      - echo Build completed on `date`
