version: 0.2

phases:
  install:
    runtime-versions:
      python: "3.7"
    commands:
      - apt-get -qq install pandoc -y
      - pip install ipython sphinx sphinx_rtd_theme sphinxcontrib-bibtex sphinx-autobuild nbsphinx -q
  pre_build:
    commands:
      - python --version
      - pip --version
  build:
    commands:
      - cd sphinx/java-intro && make clean && make html && cd ../..
      - cd sphinx/python-intro && make clean && make html && cd ../..
      - cd sphinx/pytorch-intro && make clean && make html && cd ../..
      - cd sphinx/scikit-intro && make clean && make html && cd ../..
      - cd sphinx/spark-intro && make clean && make html && cd ../..
  post_build:
    commands:
      - echo Build completed on `date`
