version: 0.2

phases:
  install:
    runtime-versions:
      python: "3.7"
    commands:
      - echo Entered the install phase...
      - pip install sphinx sphinx_rtd_theme sphinxcontrib-bibtex sphinx-autobuild nbsphinx
    finally:
      - echo Install finished
  pre_build:
    commands:
      - echo Entered the pre-build phase...
      - python --version
      - pip --version
    finally:
      - echo Prebuild finished 
  build:
    commands:
      - echo Entered the build phase...
      - cd sphinx/java-intro && make clean && make html && cd ../..
    finally:
      - echo Build finished
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
