version: "3.7"
services:
  db1:
    image: ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/db1:latest
    container_name: db1
    ports:
      - "3306:3306"
    volumes:
      - data_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
volumes:
  data_volume:
    external: True
    name: ${VOLUME_ID}
networks:
  default:
    external: true
    name: ${AWS_SECURITY_GROUP}    
x-aws-vpc: ${AWS_VPC}