version: '3'
services:
  java:
    image: oneoffcoder/book-java-intro
    ports:
      - "7770:8888"
    volumes:
      - "$HOME/git/books/docker/java-intro/ipynb:/root/ipynb"
  python:
    image: oneoffcoder/book-python-intro
    ports:
      - "7771:8888"
    volumes:
      - "$HOME/git/books/docker/python-intro/ipynb:/root/ipynb"
  pytorch:
    image: oneoffcoder/book-pytorch-intro
    ports:
      - "7772:8888"
    volumes:
      - "$HOME/git/books/docker/pytorch-intro/ipynb:/root/ipynb"
  scikit:
    image: oneoffcoder/book-scikit-intro
    ports:
      - "7773:8888"
    volumes:
      - "$HOME/git/books/docker/scikit-intro/ipynb:/root/ipynb"
  spark:
    image: oneoffcoder/book-spark-intro
    ports:
      - "7774:8888"
      - "9870:9870"
      - "8088:8088"
      - "18080:18080"
      - "9000:9000"
      - "9864:9864"
    volumes:
      - "$HOME/git/books/docker/spark-intro/ipynb:/root/ipynb"
