version: "3.7"
services:
  java:
    image: oneoffcoder/book-java-intro
    ports:
      - "7770:8888"
    volumes:
      - type: bind
        source: ./java-intro/ipynb
        target: /root/ipynb
        consistency: consistent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
  python:
    image: oneoffcoder/book-python-intro
    ports:
      - "7771:8888"
    volumes:
      - type: bind
        source: ./python-intro/ipynb
        target: /root/ipynb
        consistency: consistent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
  pytorch:
    image: oneoffcoder/book-pytorch-intro
    ports:
      - "7772:8888"
    volumes:
      - type: bind
        source: ./pytorch-intro/ipynb
        target: /root/ipynb
        consistency: consistent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
  scikit:
    image: oneoffcoder/book-scikit-intro
    ports:
      - "7773:8888"
    volumes:
      - type: bind
        source: ./scikit-intro/ipynb
        target: /root/ipynb
        consistency: consistent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
  spark:
    image: oneoffcoder/book-spark-intro
    ports:
      - "7774:8888"
      - "9870:9870"
      - "8088:8088"
      - "18080:18080"
      - "9000:9000"
      - "9864:9864"
    volumes:
      - type: bind
        source: ./spark-intro/ipynb
        target: /root/ipynb
        consistency: consistent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
