version: "3.7"
services:
  ng:
    image: ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/ww1:latest
    container_name: ww1
    ports:
      - "80:80"
    volumes:
      - data_volume:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
volumes:
  data_volume:
    external: True
    name: ${VOLUME_ID}
networks:
  default:
    external: true
    name: ${AWS_SECURITY_GROUP}
x-aws-vpc: ${AWS_VPC}